tournaments/__init__.py
from flask import Flask, render_template

def create_app():
    app = Flask(__name__)
    from .views import main
    app.register_blueprint(main)
    
    return app

tournaments/views.py
from flask import Blueprint, render_template

# Define a Blueprint named 'main' to organize routes
main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('index.html')  

@main.route('/createEvent')
def createEvent():
    return render_template('createEvent.html') 


@main.route('/eventDetails')
def eventDetails():
    return render_template('eventDetails.html') 


@main.route('/history')
def history():
    return render_template('history.html') 


tournaments/templates/createEvent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Name Naman Setia -->
    <!-- Student ID: n11882778 -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Gaming Tournament</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><b>Gaming Tournaments</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
        </a>

          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
                
              </ul>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{{ url_for('main.createEvent') }}">Create Tournament</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.history') }}">History</a>
                </li>
                
              </ul>
            
            <button class="btn btn-outline-primary">Login</button>
          </div>
        </div>
    </nav>


<main><img src="{{ url_for('static', filename='img/detailsimg.jpg') }}" class="img-fluid" alt="..."></main>

<br>
<section class="container">
    <h1 class="text-center"> Create A Tournament</h1>
    <form action="" class="w-75 mx-auto pt-4">
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Tournament Name</span>
            <input type="text" class="form-control" placeholder="Tournament Name" aria-label="Username" aria-describedby="basic-addon1">
            
        </div>
          
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Price</span>
            <input type="number" class="form-control" placeholder="Price" aria-label="Recipient's username" aria-describedby="basic-addon2">
        </div>

        <div class="input-group mb-3">

            <span class="input-group-text" id="basic-addon2">Tournament Date</span>
            <input type="date" class="form-control" placeholder="Tournament Date" aria-label="Recipient's username" aria-describedby="basic-addon2">
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Game Type</span>
            <select class="form-select" aria-label="Default select example">
                <option selected>Online</option>
                <option value="1">Duo</option>
                <option value="2">Open Challange</option>
                <option value="3">At Location</option>
            </select>
        </div>

        <div class="mb-3">
            <span class="input-group-text" id="basic-addon2">Game Description</span>
            <textarea placeholder="Enter Here" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Game Poster</span>
            <input type="file" class="form-control" id="inputGroupFile01">
        </div>
        
        <button type="submit" class="btn btn-primary w-100">Publish Tournament</button>

    </form>
       
</section>
<br>
<br>    
<footer class="text-bg-dark p-3" >
    <p class="text-center">&copy Gaming Tournaments Naman Setia @2024</p>
</footer>
</body>
</html>

tournaments/templates/eventDetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Name Naman Setia -->
    <!-- Student ID: n11882778 -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Gaming Tournament</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><b>Gaming Tournaments</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
        </a>

          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{{ url_for('main.home') }}">Home</a>

                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.createEvent') }}">Create Tournament</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.history') }}">History</a>
                </li>
                
            </ul>
            
            <button class="btn btn-outline-primary">Login</button>
          </div>
        </div>
    </nav>


<main><img src="{{ url_for('static', filename='img/detailsimg.jpg') }}" class="img-fluid" alt="..."></main>

<br>
<section class="container">
    <h1 class="text-center"> Join Tournament</h1><br>
    <div class="container">
        <div class="row d-flex flexContainer">
            <div class="fullWidth col-4">
                <img class="img-fluid" src="static/img/valomob.jpg" alt="">
            </div>
            <div class="fullWidth col-8">
                <h2 class="mt-5">Valorant</h2>
                <p><span id="gameStatus">online</span></p>
                <h1>$50</h1>
                
                <div class="row">
                    <div class="col-sm">
                        <p>Tickets</p>
                        <div class="form-floating mb-3">
                            <input type="number" class="form-control" id="floatingInput" placeholder="Enter a Number Here">
                            <label for="floatingInput">Tickets Book</label>
                        </div>
                    </div>
                    <div class="col-sm">
                        <p>Spots Available</p>
                        <div class="form-floating mb-3">
                            <input class="form-control" disabled id="floatingInput" placeholder="name@example.com">
                            <label for="floatingInput">15</label>
                        </div>
                    </div>
                </div>
                <button type="button" class="btn btn-primary w-100 "> Join Now</button>
                    
                <br>
                <br>
                <div class="card">
                    <div class="card-body">
                        <p>Gaming Tournaments encourages community involvement by letting players
                            interact through comments under the post. Players can track if they are participating in
                            tournament and all the details about the contest. This creates a place where all type of gamers
                            has a chance to show their skills to shine between other rivals</p>
                    </div>
                </div>
                
                <p></p>
                    <br><br>
            </div>
            
        </div>
    </div>
    <div class="container">
        <h1 class="text-center">Comments</h1><br>
        <div class="fullWidth card mx-auto ">
            <div class="card-body">
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Add New Comment</label>
                    <textarea placeholder="Enter Here" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        <br>
        <div class="card mx-auto">
            <div class="card-body">
                <h4>John Doe</h4>
                <p>Gaming Tournaments encourages community involvement by letting players
                    has a chance to show their skills to shine between other rivals</p>
            </div>
        </div>
        <br>
        <div class="card mx-auto">
            <div class="card-body">
                <h4>Harry Potter</h4>
                <p>Gaming Tournaments encourages community involvement by letting players
                    has a chance to show their skills to shine between other rivals</p>
            </div>
        </div>
        <br>
        <div class="card mx-auto">
            <div class="card-body">
                <h4>Jean Grey</h4>
                <p>Gaming Tournaments encourages community involvement by letting players
                    has a chance to show their skills to shine between other rivals</p>
            </div>
        </div>
        <br>
        <div class="card mx-auto">
            <div class="card-body">
                <h4>Tony Stark</h4>
                <p>Gaming Tournaments encourages community involvement by letting players
                    has a chance to show their skills to shine between other rivals</p>
            </div>
        </div>
        <br>
        <div class="card mx-auto">
            <div class="card-body">
                <h4>Bruce Banner</h4>
                <p>Gaming Tournaments encourages community involvement by letting players
                    has a chance to show their skills to shine between other rivals</p>
            </div>
        </div>
    </div>
</section>
<br>
<br>    
<footer class="text-bg-dark p-3" >
    <p class="text-center">&copy Gaming Tournaments Naman Setia @2024</p>
</footer>
</body>
</html>

tournaments/templates/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Name Naman Setia -->
    <!-- Student ID: n11882778 -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Gaming Tournament</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><b>Gaming Tournaments</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
        </a>

          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{{ url_for('main.home') }}">Home</a>

                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('main.createEvent') }}">Create Tournament</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link active" href="{{ url_for('main.history') }}">History</a>
                </li>
                
            </ul>
            
            <button class="btn btn-outline-primary">Login</button>
          </div>
        </div>
    </nav>


<main><img src="{{ url_for('static', filename='img/detailsimg.jpg') }}" class="img-fluid" alt="..."></main>

<br>
<section class="container">
    <h1 class="text-center"> Tournament Joined History</h1><br>
    <div class="container">
        <div class="card w-75 mx-auto">
            <div class="card-body">
                <div class="row d-flex flexContainer">
                    <div class="col-5 fullWidth">
                        <img class="img-fluid rounded" src="{{ url_for('static', filename='img/valorant.jpg') }}" alt="">
                    </div>
                    <div class="col-7 fullWidth">
                        <h2>Valorant</h2>
                        <h3>50$</h3>
                        <p>competitive events where teams of players battle it out to showcase their skills and strategic gameplay</p>
                        <a href="{{ url_for('main.eventDetails') }}"><button type="button" class="btn btn-primary w-100 "> View Details</button></a>
                    </div>
                    
                </div>
                
            </div>
        </div><br>
        <div class="card w-75 mx-auto">
            <div class="card-body">
                <div class="row d-flex flexContainer">
                    <div class="fullWidth col-5 ">
                        <img class="img-fluid rounded" src="static/img/gta.jpg" alt="">
                    </div>
                    <div class="col-7 fullWidth">
                        <h2>GTA V</h2>
                        <h3>25$</h3>
                        <p>Get ready for adrenaline-fueled action! Join our GTA 5 tournament, compete with the best, and seize victory. Sign up now for thrilling adventures!</p>
                        <a href="{{ url_for('main.eventDetails') }}"><button type="button" class="btn btn-primary w-100 "> View Details</button></a>
                    </div>
                    
                </div>
                
            </div>
        </div>
            <br>
        <div class="card w-75 mx-auto">
            <div class="card-body">
                <div class="row d-flex flexContainer">
                    <div class="col-5 fullWidth">
                        <img class="img-fluid rounded" src="static/img/dota.jpg" alt="">
                    </div>
                    <div class="col-7 fullWidth">
                        <h2>Dota 2</h2>
                        <h3>30$</h3>
                        <p>Gear up for the ultimate showdown! Join our Dota 2 tournament, rally your team, and conquer the battlefield. Register now for glory and epic battles!</p>
                        <a href="{{ url_for('main.eventDetails') }}"><button type="button" class="btn btn-primary w-100 "> View Details</button></a>
                    </div>
                    
                </div>
                
            </div>
        </div>
    </div>
    
</section>
<br>
<br>    
<footer class="text-bg-dark p-3" >
    <p class="text-center">&copy Gaming Tournaments Naman Setia @2024</p>
</footer>
</body>
</html>

tournaments/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Name Naman Setia -->
    <!-- Student ID: n11882778 -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - Gaming Tournament</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><b>Gaming Tournaments</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
        </a>

          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.createEvent') }}">Create Tournament</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.history') }}">History</a>
              </li>
              
            </ul>
            
            <button class="btn btn-outline-primary">Login</button>
          </div>
        </div>
    </nav>
<br>
<br>
<br>
    <div class="container">
        <div class="d-flex flexContainer">
            
            <div class="fullWidth col-4 ">
                <h1 class="text-center mt-5">Join A Tournament</h1><br><br>
                <p class="text-center">Gaming Tournaments encourages community involvement by letting players
                    interact through comments under the post. Players can track if they are participating in
                    tournament and all the details about the contest. This creates a place where all type of gamers
                    has a chance to show their skills to shine between other rivals</p>
                    <br><br>
                <div class=" text-center">
                    <button type="button" class="btn btn-primary"> Join Now</button>
                  </div>
                  <br>
            </div>
            <div class="col-8 fullWidth px-4 ">
                <img class="img-fluid rounded" src="{{ url_for('static', filename='img/banner7.jpg') }}" alt="">
            </div>
        </div>
    </div>
    <br><br>
    <hr>
    <br><br>

<div class="">
    <h1 class="text-center">Best Tournaments</h1>
    <br><br>

    <div class="row row-cols-1 row-cols-md-4 g-5 mx-5">
        <div class="col">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='img/valorant.jpg') }}" class="card-img-top" alt="static/img/banner7.jpg">
                <div class="card-body">
                    <h5 class="card-title">Valorant</h5>
                    <p class="card-text">competitive events where teams of players battle it out to showcase their skills and strategic gameplay</p>
                </div>
                <a href="{{ url_for('main.eventDetails') }}" class="btn btn-primary w-50 mx-auto">Join Now</a><br>
                <div class="card-footer">
                    <small class="text-body-secondary">Open</small>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='img/pubg.jpg') }}" class="card-img-top" alt="static/img/banner7.jpg">
                <div class="card-body">
                    <h5 class="card-title">PUBG</h5>
                    <p class="card-text">Join us for an epic PUBG tournament! Showcase your skills, compete for glory, and win amazing prizes. Sign up now!</p>
                </div>
                <a href="{{ url_for('main.eventDetails') }}" class="btn btn-primary w-50 mx-auto">Join Now</a><br>
                <div class="card-footer">
                    <small class="text-body-secondary">Open</small>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='img/gta.jpg') }}" class="card-img-top" alt="static/img/banner7.jpg">
                <div class="card-body">
                    <h5 class="card-title">GTA V</h5>
                    <p class="card-text">Get ready for adrenaline-fueled action! Join our GTA 5 tournament, compete with the best, and seize victory. Sign up now for thrilling adventures!</p>
                </div>
                <a href="#" class="btn btn-secondary w-50 mx-auto">Join Now</a><br>
                <div class="card-footer">
                    <small class="text-body-secondary">Inactive</small>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='img/csgo.jpg') }}" class="card-img-top" alt="static/img/banner7.jpg">
                <div class="card-body">
                    <h5 class="card-title">Counter-Strike</h5>
                    <p class="card-text">Join our Counter-Strike tournament! Engage in intense battles, showcase your strategy, and dominate the competition. Register now for thrilling gameplay and epic victories!</p>
                </div>
                <a href="#" class="btn btn-secondary w-50 mx-auto">Join Now</a><br>
                <div class="card-footer">
                    <small class="text-body-secondary">Sold out</small>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='img/dota.jpg') }}" class="card-img-top" alt="static/img/banner7.jpg">
                <div class="card-body">
                    <h5 class="card-title">Dota 2</h5>
                    <p class="card-text">Gear up for the ultimate showdown! Join our Dota 2 tournament, rally your team, and conquer the battlefield. Register now for glory and epic battles!</p>
                </div>
                <a href="#" class="btn btn-secondary w-50 mx-auto">Join Now</a><br>
                <div class="card-footer">
                    <small class="text-body-secondary">Cancelled</small>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='img/league.jpg') }}" class="card-img-top" alt="static/img/banner7.jpg">
                <div class="card-body">
                    <h5 class="card-title">League of Legends</h5>
                    <p class="card-text">A popular MOBA game where two teams of five players compete to destroy the enemy's nexus.</p>
                </div>
                <a href="{{ url_for('main.eventDetails') }}" class="btn btn-primary w-50 mx-auto">Join Now</a><br>
                <div class="card-footer">
                    <small class="text-body-secondary">Open</small>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='img/apex.jpg') }}" class="card-img-top" alt="static/img/banner7.jpg">
                <div class="card-body">
                    <h5 class="card-title">Apex Legends</h5>
                    <p class="card-text">A battle royale game where players form teams of three to compete for victory.</p>
                </div>
                <a href="{{ url_for('main.eventDetails') }}" class="btn btn-primary w-50 mx-auto">Join Now</a><br>
                <div class="card-footer">
                    <small class="text-body-secondary">Open</small>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <img src="{{ url_for('static', filename='img/overwatch.jpg') }}" class="card-img-top" alt="static/img/banner7.jpg">
                <div class="card-body">
                    <h5 class="card-title">Overwatch</h5>
                    <p class="card-text">A hero shooter game where players choose unique heroes with distinct abilities to battle on maps with various objectives.</p>
                </div>
                <a href="{{ url_for('main.eventDetails') }}" class="btn btn-primary w-50 mx-auto">Join Now</a><br>
                <div class="card-footer">
                    <small class="text-body-secondary">Open</small>
                </div>
            </div>
        </div>
        
        
    </div>
</div>

<br>
<br>
<br>    
<footer class="text-bg-dark p-3" >
    <p class="text-center">&copy Gaming Tournaments Naman Setia @2024</p>
</footer>
</body>
</html>